name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
#Allows me to run this workflow manually fom Action tabs
  workflow_dispatch:

jobs:
  build:
    # We use ubuntu-latest because it has the C libraries and 
    # Android SDK pre-installed, avoiding the AAPT2 errors you saw on Windows.
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Verify Environment
      run: |
        echo "JAVA_HOME: $JAVA_HOME"
        java -version

    - name: Run a one line script
      run: echo Hello World
      
    - name: Run a multi line script
      run: |
        echo "Add another action to build,"
        echo "Test and deploy your project"
        
  lint:
    runs-on: ubuntu-latest

    # Permission needed for hardware acceleration on Linux runners
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run lint
        run: ./gradlew lintDebug --continue

      - name: Upload html test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: app/build/reports/lint-results-debug.html

  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # This runs all tests in the 'test' folder of your app module
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest


       # 2. Run Instrumented Tests (Espresso/Compose)
      # This uses the ReactiveCircus emulator action which is the industry standard
      - name: Run Instrumented Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis
          arch: x86_64
          profile: Nexux 6
          script: ./gradlew connectedDebugAndroidTest

      - name: Upload Test Report
        if: always() # Upload even if tests fail so you can see why
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: app/build/reports/tests/testDebugUnitTest/


